name = "JuliaDB"
uuid = "a93385a2-3734-596a-9a66-3cfbb77141e6"
version = "0.13.1"

[deps]
Dagger = "d58978e5-989f-55fb-8d15-ea34adc7bf54"
DataValues = "e7dc6d0d-1eca-5fa6-8ad6-5aecde8b7ea5"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
IndexedTables = "6deec6e2-d858-57c5-ab9b-e6ca5bd20e43"
MemPool = "f9f48841-c794-520a-933b-121f7ba6ed94"
Nullables = "4d1e1d77-625e-5b40-9113-a560ec7a8ecd"
OnlineStats = "a15396b6-48d5-5d58-9928-6d29437db91e"
OnlineStatsBase = "925886fa-5bf2-5e8e-b522-a9147a512338"
PooledArrays = "2dfb63ee-cc39-5dd5-95bd-886bf059d720"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TextParse = "e0df1984-e451-5cb5-8b61-797a481e67e3"
WeakRefStrings = "ea10d353-3f73-51f8-a26c-33c1cb351aa5"

[compat]
Dagger = "0.8"
DataValues = "= 0.4.12"
Glob = "= 1.2.0"
IndexedTables = "= 0.12.4"
MemPool = "= 0.2.0"
Nullables = "= 0.0.8"
OnlineStats = "= 1.0.2"
OnlineStatsBase = "= 1.0.2"
PooledArrays = "= 0.5.2"
RecipesBase = "= 0.7.0"
StatsBase = "= 0.32.0, 0.33"
TextParse = "= 0.9.1"
WeakRefStrings = "= 0.6.1"
julia = "1"

[extras]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Dates", "Random", "Test"]
