[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
IndexedTables = "6deec6e2-d858-57c5-ab9b-e6ca5bd20e43"
JuliaDB = "a93385a2-3734-596a-9a66-3cfbb77141e6"
OnlineStats = "a15396b6-48d5-5d58-9928-6d29437db91e"
RDatasets = "ce6b1742-4840-55fa-b093-852dadbb1d8b"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
